a = float(input("Please enter first number"))
b = float(input("Please enter second number number"))
print(a + b)
print("Addition is", a+b)
print(" Substraction is", a-b)
print(" Multiplication is",a*b)
print("Division is", a/b)
print("Modulous is", a%b)
print("Exponent is", a**b)
print("Floor division is", a//b)
#making a different calculator
first = input("first number")
operators = input("enter operators(+,-,*,/,%,//) :")
second = input("second number")
first = int(first)
second = int(second)